import { Lead } from "./types";

export const seedLeads: Lead[] = [
  {
    id: "1",
    firstName: "Jorge",
    lastName: "Ruiz",
    email: "jorge.ruiz@example.com",
    country: "Mexico",
    linkedIn: "https://linkedin.com/in/jorgeruiz",
    visaInterests: ["O-1"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "I need help with my O-1 visa application.",
    status: "PENDING",
    submittedAt: "2024-02-02T14:45:00.000Z",
  },
  {
    id: "2",
    firstName: "Bahar",
    lastName: "Zamir",
    email: "bahar.zamir@example.com",
    country: "Mexico",
    linkedIn: "https://linkedin.com/in/baharzamir",
    visaInterests: ["EB-1A"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "Looking into EB-1A options for my research background.",
    status: "PENDING",
    submittedAt: "2024-02-02T14:45:00.000Z",
  },
  {
    id: "3",
    firstName: "Mary",
    lastName: "Lopez",
    email: "mary.lopez@example.com",
    country: "Brazil",
    linkedIn: "https://linkedin.com/in/marylopez",
    visaInterests: ["EB-2 NIW"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "Interested in EB-2 NIW for my engineering career.",
    status: "PENDING",
    submittedAt: "2024-02-02T14:45:00.000Z",
  },
  {
    id: "4",
    firstName: "Li",
    lastName: "Zijin",
    email: "li.zijin@example.com",
    country: "South Korea",
    linkedIn: "https://linkedin.com/in/lizijin",
    visaInterests: ["O-1", "EB-1A"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "Exploring visa options for my tech career.",
    status: "PENDING",
    submittedAt: "2024-02-02T14:45:00.000Z",
  },
  {
    id: "5",
    firstName: "Mark",
    lastName: "Antonov",
    email: "mark.antonov@example.com",
    country: "Russia",
    linkedIn: "https://linkedin.com/in/markantonov",
    visaInterests: ["I don't know"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "Not sure which visa category is right for me.",
    status: "PENDING",
    submittedAt: "2024-02-02T14:45:00.000Z",
  },
  {
    id: "6",
    firstName: "Jane",
    lastName: "Ma",
    email: "jane.ma@example.com",
    country: "Mexico",
    linkedIn: "https://linkedin.com/in/janema",
    visaInterests: ["EB-2 NIW"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "Need assessment for NIW based on my PhD research.",
    status: "PENDING",
    submittedAt: "2024-02-02T14:45:00.000Z",
  },
  {
    id: "7",
    firstName: "Anand",
    lastName: "Jain",
    email: "anand.jain@example.com",
    country: "Mexico",
    linkedIn: "https://linkedin.com/in/anandjain",
    visaInterests: ["O-1", "EB-1A"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "Would like to understand my options as a startup founder.",
    status: "REACHED_OUT",
    submittedAt: "2024-02-02T14:45:00.000Z",
  },
  {
    id: "8",
    firstName: "Anna",
    lastName: "Voronova",
    email: "anna.voronova@example.com",
    country: "France",
    linkedIn: "https://linkedin.com/in/annavoronova",
    visaInterests: ["O-1"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "Looking for O-1 visa assessment for my art career.",
    status: "PENDING",
    submittedAt: "2024-02-02T14:45:00.000Z",
  },
  {
    id: "9",
    firstName: "Krishna",
    lastName: "Guda",
    email: "krishna.guda@example.com",
    country: "India",
    linkedIn: "https://www.linkedin.com/in/krishnamohanguda/",
    visaInterests: ["I don't know"],
    resumePath: null,
    resumeFileName: "resume.pdf",
    helpMessage: "I want to get my green card faster. I have the I-140 approved.",
    status: "PENDING",
    submittedAt: "2024-02-03T10:15:00.000Z",
  },
];
