import { Lead } from "./types";

export const seedLeads: Lead[] = [
  {
    id: "1",
    firstName: "Jorge",
    lastName: "Ruiz",
    email: "jorge.ruiz@example.com",
    country: "Mexico",
    linkedIn: "https://linkedin.com/in/jorgeruiz",
    visaInterests: ["O-1"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "I need help with my O-1 visa application.",
    status: "PENDING",
    submittedAt: "2024-02-02T14:45:00.000Z",
  },
  {
    id: "2",
    firstName: "Bahar",
    lastName: "Zamir",
    email: "bahar.zamir@example.com",
    country: "Mexico",
    linkedIn: "https://linkedin.com/in/baharzamir",
    visaInterests: ["EB-1A"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "Looking into EB-1A options for my research background.",
    status: "PENDING",
    submittedAt: "2024-02-02T14:45:00.000Z",
  },
  {
    id: "3",
    firstName: "Mary",
    lastName: "Lopez",
    email: "mary.lopez@example.com",
    country: "Brazil",
    linkedIn: "https://linkedin.com/in/marylopez",
    visaInterests: ["EB-2 NIW"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "Interested in EB-2 NIW for my engineering career.",
    status: "PENDING",
    submittedAt: "2024-02-02T14:45:00.000Z",
  },
  {
    id: "4",
    firstName: "Li",
    lastName: "Zijin",
    email: "li.zijin@example.com",
    country: "South Korea",
    linkedIn: "https://linkedin.com/in/lizijin",
    visaInterests: ["O-1", "EB-1A"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "Exploring visa options for my tech career.",
    status: "PENDING",
    submittedAt: "2024-02-02T14:45:00.000Z",
  },
  {
    id: "5",
    firstName: "Mark",
    lastName: "Antonov",
    email: "mark.antonov@example.com",
    country: "Russia",
    linkedIn: "https://linkedin.com/in/markantonov",
    visaInterests: ["I don't know"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "Not sure which visa category is right for me.",
    status: "PENDING",
    submittedAt: "2024-02-02T14:45:00.000Z",
  },
  {
    id: "6",
    firstName: "Jane",
    lastName: "Ma",
    email: "jane.ma@example.com",
    country: "Mexico",
    linkedIn: "https://linkedin.com/in/janema",
    visaInterests: ["EB-2 NIW"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "Need assessment for NIW based on my PhD research.",
    status: "PENDING",
    submittedAt: "2024-02-02T14:45:00.000Z",
  },
  {
    id: "7",
    firstName: "Anand",
    lastName: "Jain",
    email: "anand.jain@example.com",
    country: "Mexico",
    linkedIn: "https://linkedin.com/in/anandjain",
    visaInterests: ["O-1", "EB-1A"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "Would like to understand my options as a startup founder.",
    status: "REACHED_OUT",
    submittedAt: "2024-02-02T14:45:00.000Z",
  },
  {
    id: "8",
    firstName: "Anna",
    lastName: "Voronova",
    email: "anna.voronova@example.com",
    country: "France",
    linkedIn: "https://linkedin.com/in/annavoronova",
    visaInterests: ["O-1"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "Looking for O-1 visa assessment for my art career.",
    status: "PENDING",
    submittedAt: "2024-02-02T14:45:00.000Z",
  },
  {
    id: "9",
    firstName: "Krishna",
    lastName: "Guda",
    email: "krishna.guda@example.com",
    country: "India",
    linkedIn: "https://www.linkedin.com/in/krishnamohanguda/",
    visaInterests: ["I don't know"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "I want to get my green card faster. I have the I-140 approved.",
    status: "PENDING",
    submittedAt: "2024-02-03T10:15:00.000Z",
  },
  {
    id: "10",
    firstName: "Sofia",
    lastName: "Petrov",
    email: "sofia.petrov@example.com",
    country: "Ukraine",
    linkedIn: "https://linkedin.com/in/sofiapetrov",
    visaInterests: ["O-1"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "I'm a software architect looking to relocate to the US.",
    status: "PENDING",
    submittedAt: "2024-02-04T09:30:00.000Z",
  },
  {
    id: "11",
    firstName: "Carlos",
    lastName: "Mendez",
    email: "carlos.mendez@example.com",
    country: "Colombia",
    linkedIn: "https://linkedin.com/in/carlosmendez",
    visaInterests: ["EB-2 NIW"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "PhD in biomedical engineering, exploring NIW options.",
    status: "REACHED_OUT",
    submittedAt: "2024-02-04T11:00:00.000Z",
  },
  {
    id: "12",
    firstName: "Yuki",
    lastName: "Tanaka",
    email: "yuki.tanaka@example.com",
    country: "Japan",
    linkedIn: "https://linkedin.com/in/yukitanaka",
    visaInterests: ["O-1", "EB-1A"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "Award-winning designer seeking extraordinary ability visa.",
    status: "PENDING",
    submittedAt: "2024-02-05T08:15:00.000Z",
  },
  {
    id: "13",
    firstName: "Priya",
    lastName: "Sharma",
    email: "priya.sharma@example.com",
    country: "India",
    linkedIn: "https://linkedin.com/in/priyasharma",
    visaInterests: ["EB-1A"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "Published researcher with 50+ citations, exploring EB-1A.",
    status: "PENDING",
    submittedAt: "2024-02-05T14:20:00.000Z",
  },
  {
    id: "14",
    firstName: "Ahmed",
    lastName: "Hassan",
    email: "ahmed.hassan@example.com",
    country: "Egypt",
    linkedIn: "https://linkedin.com/in/ahmedhassan",
    visaInterests: ["O-1"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "Fintech founder with international press coverage.",
    status: "REACHED_OUT",
    submittedAt: "2024-02-06T10:45:00.000Z",
  },
  {
    id: "15",
    firstName: "Elena",
    lastName: "Popova",
    email: "elena.popova@example.com",
    country: "Russia",
    linkedIn: "https://linkedin.com/in/elenapopova",
    visaInterests: ["EB-2 NIW", "EB-1A"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "AI researcher at a top university, need visa guidance.",
    status: "PENDING",
    submittedAt: "2024-02-06T16:30:00.000Z",
  },
  {
    id: "16",
    firstName: "Diego",
    lastName: "Silva",
    email: "diego.silva@example.com",
    country: "Brazil",
    linkedIn: "https://linkedin.com/in/diegosilva",
    visaInterests: ["O-1"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "Professional musician with Grammy nomination.",
    status: "PENDING",
    submittedAt: "2024-02-07T09:00:00.000Z",
  },
  {
    id: "17",
    firstName: "Mei",
    lastName: "Chen",
    email: "mei.chen@example.com",
    country: "China",
    linkedIn: "https://linkedin.com/in/meichen",
    visaInterests: ["EB-1A"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "Senior data scientist at a FAANG company seeking EB-1A.",
    status: "PENDING",
    submittedAt: "2024-02-07T13:45:00.000Z",
  },
  {
    id: "18",
    firstName: "Omar",
    lastName: "Al-Farsi",
    email: "omar.alfarsi@example.com",
    country: "UAE",
    linkedIn: "https://linkedin.com/in/omaralfarsi",
    visaInterests: ["I don't know"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "Serial entrepreneur, not sure which visa fits best.",
    status: "REACHED_OUT",
    submittedAt: "2024-02-08T11:20:00.000Z",
  },
  {
    id: "19",
    firstName: "Lucia",
    lastName: "Fernandez",
    email: "lucia.fernandez@example.com",
    country: "Argentina",
    linkedIn: "https://linkedin.com/in/luciafernandez",
    visaInterests: ["O-1", "EB-2 NIW"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "Biotech startup founder with multiple patents.",
    status: "PENDING",
    submittedAt: "2024-02-08T15:10:00.000Z",
  },
  {
    id: "20",
    firstName: "Tomas",
    lastName: "Novak",
    email: "tomas.novak@example.com",
    country: "Czech Republic",
    linkedIn: "https://linkedin.com/in/tomasnovak",
    visaInterests: ["EB-1A"],
    resumePath: null,
    resumeFileName: null,
    helpMessage: "CTO of a venture-backed startup, exploring options.",
    status: "PENDING",
    submittedAt: "2024-02-09T08:00:00.000Z",
  },
];
